//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvoi.Backen.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string RegisteredName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string WebURL { get; set; }
        public System.DateTime DateModifield { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Logo { get; set; }
        public Nullable<int> AddressId { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
